### PR TITLE
stream/tcp: Test verifies the behavior when direction of TCP flow is …

### PR DESCRIPTION
**Pull request by ilya-bakhtin**
…changed by the probing parser.

pcap file contains 2 http transactions. The request is missing for the first one.
The second transaction is fully complete. So eve.json must contain one and only anomaly event.

### CODE REVIEW

**Comment by ilya-bakhtin** [comment]
requires suricata pr https://github.com/OISF/suricata/pull/4956

**Review by catenacyber — CHANGES_REQUESTED** [review]
Thanks for this.
Could you add a README.md file to explain the purpose of this test ?
(basically what has been discussed in Github, so that it is in the code)

**Comment by ilya-bakhtin** [comment]
please see https://github.com/OISF/suricata-verify/pull/311

**Comment by catenacyber** [comment]
Closing in favor of #311

**Pull request closed without merging**
