### PR TITLE
stateful drop on dsize sig/v4

### PR DESCRIPTION
**Pull request by inashivb**
## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/5578

Previous PR: https://github.com/OISF/suricata-verify/pull/1424

Changes since v3:
- rebased
- min-version added

### CODE REVIEW

**Comment by inashivb** [comment]
> Is there a suricata PR with this ?

hmm I just realized that I blindly added the min-version. Shouldn't have as the issue only exists on 6.0.x and the last PR I can trace was https://github.com/OISF/suricata/pull/9664

**Comment by catenacyber** [comment]
So, the question is for Victor if we still want https://redmine.openinfosecfoundation.org/issues/5578 for 6...

**Comment by inashivb** [comment]
> can you please set descriptive subjects in PRs?

Tried to add something. Please check. Sorry but I don't have much idea about this. I just took your s-v PR and rebased it earlier so the tests would pass.

**Comment by inashivb** [comment]
> Should this be rebased or closed ?

Closed, I think. Didn't know there was a newer version that has already been merged.

**Comment by catenacyber** [comment]
cf #1803

**Pull request closed without merging**
