### PR TITLE
createst: Create a default README with every test

### PR DESCRIPTION
**Pull request by AkakiAlice**
Feature: #5210
Previous PR: #1010

Description:
- Replace name and email autocompletion to manual completion.

Link to the redmine ticket: https://redmine.openinfosecfoundation.org/issues/5210

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Ran a simple test and this seems to work as expected, changes requested in the prior version seem to have been incorporated, as well. Thanks! :)

**Review by jasonish — APPROVED** [review]
Looks OK to me.

**Comment by inashivb** [comment]
Thank you for your contribution, @AkakiAlice ! :)
Based on suggestions by Jason, I have made some updates and staged a new PR for merge/review. #1129

**Comment by inashivb** [comment]
Your PR was merged as a part of https://github.com/OISF/suricata-verify/pull/1156. Thank you for your contribution! :)

**Pull request closed without merging**
