### PR TITLE
threshold-config: New test for issue in 2190

### PR DESCRIPTION
**Pull request by jlucovsky**
This commit adds a test case for large IP address handling in the
threshold.config file.

### CODE REVIEW

**Comment by catenacyber** [comment]
There is now a suricata PR about this, right @jlucovsky ?

**Comment by jlucovsky** [comment]
> There is now a suricata PR about this, right @jlucovsky ?

https://github.com/OISF/suricata/pull/5628

**Comment by catenacyber** [comment]
@jlucovsky did you do the back port for 6 ?

**Comment by catenacyber** [comment]
@jlucovsky could you rebase to see if it passes all branches now ?

**Comment by jlucovsky** [comment]
> @jlucovsky could you rebase to see if it passes all branches now ?

Rebase passes all tests with `master-6.0.x` -- will rebuild the pr.

**Comment by jlucovsky** [comment]
Continued in #514

**Pull request closed without merging**
