### PR TITLE
snmp rdp alert metadata/v1

### PR DESCRIPTION
**Pull request by jasonish**
- snmp-v2c-get: test snmp metadata in alert
- rdp-protocol: test rdp metadata in alert

Requires Suricata PR.

### CODE REVIEW

**Comment by victorjulien** [comment]
Is the snmp one supposed to include more than just a rule?

**Comment by jasonish** [comment]
> Is the snmp one supposed to include more than just a rule?

Ah yeah. Its supposed to check that there is an snmp object in the alert.

**Comment by jasonish** [comment]
> Ah yeah. Its supposed to check that there is an snmp object in the alert.

Resolved within this PR.

**Comment by victorjulien** [comment]
Had to add a fix for suricata 5 too.

Merged in #298

**Pull request closed without merging**
