### PR TITLE
README/help: add info on IPS mode tests creation - v3

### PR DESCRIPTION
**Pull request by jufajardini**
Previous PR: https://github.com/OISF/suricata-verify/pull/1965

Describe changes:
- it's not a straightforward process to use the test name alternative with createst, so I've removed that association from the README and createst help text.
- remove mention to unrelated ticket from 540b1a5a6fad675bebc85efdfb3b0a1b1dae141b

## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket:
https://redmine.openinfosecfoundation.org/issues/7039

### CODE REVIEW

**Review by inashivb — COMMENTED** [review]
The changes look good to me. The PR and ticket look unrelated now.
Ticket seems to be about explaining/adding `simulate-ips` to createst. Could you please fix the ticket or the PR as seems fit?

**Comment by jufajardini** [comment]
> The changes look good to me. The PR and ticket look unrelated now. Ticket seems to be about explaining/adding `simulate-ips` to createst. Could you please fix the ticket or the PR as seems fit?

Updated the ticket! 🙇🏽

**Review by inashivb — APPROVED** [review]
LGTM 🚀

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
When will you merge this Victor ? Do you have some tool that takes this ?
This is just doc, no need to test...

**Comment by victorjulien** [comment]
Merged in #2049, thanks!

**Pull request closed without merging**
