### PR TITLE
Ssh banner test 4903 v1

### PR DESCRIPTION
**Pull request by TheKharleeci**

### CODE REVIEW

**Comment by inashivb** [comment]
Hi @TheKharleeci !
I'd suggest reading the README of this project. It'll give you a better idea of what a minimal test must comprise of and how can you create tests.
In general, if we are testing something, we are usually matching it against an expected output. Like, if you're running A then B must be the output, if B is in fact the output then the test should pass else fail.
We cannot do anything with just the rules. We must check what would the rules be applied to and what is our expected output.

**Comment by TheKharleeci** [comment]
> Hi @TheKharleeci ! I'd suggest reading the README of this project. It'll give you a better idea of what a minimal test must comprise of and how can you create tests. In general, if we are testing something, we are usually matching it against an expected output. Like, if you're running A then B must be the output, if B is in fact the output then the test should pass else fail. We cannot do anything with just the rules. We must check what would the rules be applied to and what is our expected output.

Ok. you mean adding the filters in the test.yaml to validate the output.

**Comment by inashivb** [comment]
> > Hi @TheKharleeci ! I'd suggest reading the README of this project. It'll give you a better idea of what a minimal test must comprise of and how can you create tests. In general, if we are testing something, we are usually matching it against an expected output. Like, if you're running A then B must be the output, if B is in fact the output then the test should pass else fail. We cannot do anything with just the rules. We must check what would the rules be applied to and what is our expected output.
> 
> Ok. you mean adding the filters in the test.yaml to validate the output.

Yes, please. README shows a script called `createst.py` that will do everything for you.

**Comment by inashivb** [comment]
Replaced w #618

**Pull request closed without merging**
