### PR TITLE
dns: adds test for sshfp

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/5642
Or rather https://redmine.openinfosecfoundation.org/issues/6478

But I think there should be its own subticket for dns

Meant to pass with https://github.com/OISF/suricata/pull/10193

### CODE REVIEW

**Comment by catenacyber** [comment]
Current failure :
```
/Users/catena/catena/prod/suricata-verify/tests/dns/dns-sshfp/output/eve.json - INVALID. Errors:
1./dns/answers/0 Additional properties are not allowed ('sshfp' was unexpected)
2./dns/answers/1 Additional properties are not allowed ('sshfp' was unexpected)
3./dns/grouped Additional properties are not allowed ('SSHFP' was unexpected)
4./dns Additional properties are not allowed ('tc' was unexpected)
===> dns-sshfp: FAILED: Invalid JSON schema
```

@jasonish is this normal to have uppercase dns.grouped.SSHFP ?

**Comment by jasonish** [comment]
> @jasonish is this normal to have uppercase dns.grouped.SSHFP ?

Normal I don't know, per our code its expected - all the type names are logged in uppercase in the groupings.

**Comment by catenacyber** [comment]
> > @jasonish is this normal to have uppercase dns.grouped.SSHFP ?
> 
> Normal I don't know, per our code its expected - all the type names are logged in uppercase in the groupings.

@hadiqaalamdar your job is to make this SV test pass then ;-) also with `dns.grouped.SSHFP`

**Comment by hadiqaalamdar** [comment]
created the schema.json PR: https://github.com/OISF/suricata/pull/10401

**Comment by hadiqaalamdar** [comment]
New schema.json PR: https://github.com/OISF/suricata/pull/10429

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #1663, thanks!

**Pull request closed without merging**
