### PR TITLE
smb: tests for reversed smb - v1

### PR DESCRIPTION
**Pull request by jasonish**
Test that SMB that is seen in the wrong direction (requests from server
to client, and replies from client to server) alert.

Requires Suricata PR https://github.com/OISF/suricata/pull/7084 as well as some
not yet implemented frame alerting support.

https://redmine.openinfosecfoundation.org/issues/5826

### CODE REVIEW

**Comment by catenacyber** [comment]
Suricata PR was merged, could we run CI again ?

**Comment by jasonish** [comment]
> Suricata PR was merged, could we run CI again ?

Looks like it also requires events on frames to be implemented in Suricata's frame support.

**Comment by catenacyber** [comment]
> > Suricata PR was merged, could we run CI again ?
> 
> Looks like it also requires events on frames to be implemented in Suricata's frame support.

Is there a redmine ticket to track this ?

**Comment by catenacyber** [comment]
> Is there a redmine ticket to track this ?

ping @jasonish ?

**Comment by jasonish** [comment]
> > Is there a redmine ticket to track this ?
> 
> ping @jasonish ?

There is now: https://redmine.openinfosecfoundation.org/issues/5826

**Pull request closed without merging**
