### PR TITLE
detect-proto: add a test for DNS detected as DCERPC by PM

### PR DESCRIPTION
**Pull request by ilya-bakhtin**
a replacement of https://github.com/OISF/suricata-verify/pull/1989

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Test looks good to me.

a README.md file could be added, mentioning the redmine ticket
The redmine ticket number could also be included in the commit message.

**Comment by inashivb** [comment]
> Test looks good to me.
> 
> a README.md file could be added, mentioning the redmine ticket The redmine ticket number could also be included in the commit message.

Agreed w Philippe. The test is too vague in itself although correct.
Also, a new rebased PR can show if those weird failures on `main-7.0.x` still exist.

**Comment by catenacyber** [comment]
> The test is too vague

How so ?
Did you rather mean that the point of the test is not enough documented ?

**Comment by inashivb** [comment]
> > The test is too vague
> 
> How so ? Did you rather mean that the point of the test is not enough documented ?

yes. Sorry for being unclear.

**Comment by catenacyber** [comment]
Replaced by #2151 if I am not mistaken

**Pull request closed without merging**
