### PR TITLE
Dcerpc logging/v2

### PR DESCRIPTION
**Pull request by inashivb**
Suricata PR to go with this: https://github.com/OISF/suricata/pull/5036

Changes since the last time: Made opnum a part of request array with JsonBuilder as that's where it belongs.

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you add a test for UDP as well?

**Comment by victorjulien** [comment]
None of the tests seem to have multiple frags in the stub data. Would be good to find (or create) an example of that and add it as a test.

**Comment by victorjulien** [comment]
This does not pass with #5055

**Comment by inashivb** [comment]
> This does not pass with [OISF/suricata#5055](https://github.com/OISF/suricata/pull/5055)

Yes. More info was added to the logger so it won't match. Looking for multi frag pcaps to address all the comments on this PR. Shal send a new one soon.

**Comment by inashivb** [comment]
Replaced with #276

**Pull request closed without merging**
