### PR TITLE
framework: consistency check for flow app-layer stats

### PR DESCRIPTION
**Pull request by catenacyber**
Replaces #1061 by taking care that `dns` flows are split in stats in `dns_udp` and `dns_tcp`

### CODE REVIEW

**Comment by catenacyber** [comment]
Interesting : http-connect-simple counts 2 http flows in stats because of protocol detection being run again...
Thoughts in this ?

**Comment by catenacyber** [comment]
@jasonish do you think 
`jq 'select(.event_type=="flow" and .app_proto=="ftp") | .app_proto'  log/eve.json | wc -l` and `jq 'select(.event_type=="stats") | .stats."app_layer".flow.ftp' log/eve.json` should always yield the same results ? Also when there is a protocol change ?

**Comment by jasonish** [comment]
> @jasonish do you think `jq 'select(.event_type=="flow" and .app_proto=="ftp") | .app_proto' log/eve.json | wc -l` and `jq 'select(.event_type=="stats") | .stats."app_layer".flow.ftp' log/eve.json` should always yield the same results ? Also when there is a protocol change ?

My guess is probably, but maybe some edge cases where not?

**Comment by catenacyber** [comment]
So, closing this as what we want to check is not universally true...

**Pull request closed without merging**
