### PR TITLE
tests: add multi-tenancy tests

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6549

S-V backport PR was merged cf https://github.com/OISF/suricata/pull/10022

https://github.com/OISF/suricata-verify/pull/1478 rebased to rerun CI

### CODE REVIEW

**Comment by catenacyber** [comment]
Do you know why these tests fail @jlucovsky ?

**Comment by jlucovsky** [comment]
> Do you know why these tests fail @jlucovsky ?

I'm looking, the 6.0.x tests use debug-validation:
```
 suricata: util-var-name.c:138: VarNameStoreDestroy: Assertion `!((vn->ref_cnt > 0))' failed.
```

**Comment by catenacyber** [comment]
Thanks Jeff

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
replaced by #1600

**Pull request closed without merging**
