### PR TITLE
test: Add byte_math test

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #229

This update includes
- Version specifiers to handle message differences
- Additional test case for 5.x

Companion PR: [Suricata PR#4916](https://github.com/OISF/suricata/pull/4916)

### CODE REVIEW

**Comment by victorjulien** [comment]
On several dists I get:
```
 ===> bug-3515: Traceback (most recent call last):
  File "../suricata-verify/run.py", line 941, in <module>
    sys.exit(main())
  File "../suricata-verify/run.py", line 919, in main
    results = test_runner.run()
  File "../suricata-verify/run.py", line 550, in run
    self.check_requires()
  File "../suricata-verify/run.py", line 468, in check_requires
    if not is_version_compatible(version=min_version,
  File "../suricata-verify/run.py", line 278, in is_version_compatible
    if not func(suri_version, config_version):
  File "../suricata-verify/run.py", line 181, in is_gte
    if v1.minor < v2.minor:
TypeError: '<' not supported between instances of 'int' and 'NoneType'
ERROR: Job failed: exit code 1
```

**Comment by jlucovsky** [comment]
> On several dists I get:
> 
> ```
>  ===> bug-3515: Traceback (most recent call last):
>   File "../suricata-verify/run.py", line 941, in <module>
>     sys.exit(main())
>   File "../suricata-verify/run.py", line 919, in main
>     results = test_runner.run()
>   File "../suricata-verify/run.py", line 550, in run
>     self.check_requires()
>   File "../suricata-verify/run.py", line 468, in check_requires
>     if not is_version_compatible(version=min_version,
>   File "../suricata-verify/run.py", line 278, in is_version_compatible
>     if not func(suri_version, config_version):
>   File "../suricata-verify/run.py", line 181, in is_gte
>     if v1.minor < v2.minor:
> TypeError: '<' not supported between instances of 'int' and 'NoneType'
> ERROR: Job failed: exit code 1
> ```

Ok ... The change to `run.py` is no longer needed and doesn't work with python 3. Removing this change and will submit a new pr.

**Comment by jlucovsky** [comment]
Continued in #270

**Comment by victorjulien** [comment]
I merged this one minus the runner commit. Hope its the same as #270.

**Pull request closed without merging**
