### PR TITLE
test/from_base64: from_base64 transform test

### PR DESCRIPTION
**Pull request by jlucovsky**
Issue: 5220
This commit adds a simple test case for the from_base64 transform.

### CODE REVIEW

**Comment by jasonish** [comment]
False sense of test passing. It checks for a file that doesn't exist.  I wonder if we should do that anymore, due to this false sense that it passes.  I'd rather have it fail until its really passes.

**Comment by jlucovsky** [comment]
> False sense of test passing. It checks for a file that doesn't exist. I wonder if we should do that anymore, due to this false sense that it passes. I'd rather have it fail until its really passes.

The Suricata PR hasn't been merged yet and is still in draft status.

**Comment by catenacyber** [comment]
What is the draft PR number ?

**Comment by catenacyber** [comment]
Seems to be https://github.com/OISF/suricata/pull/7233

**Comment by catenacyber** [comment]
Closing as https://github.com/OISF/suricata/pull/7233 was closed, right @jlucovsky ?

**Pull request closed without merging**
