### PR TITLE
http2: check for http_response_line exact content

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6547

### CODE REVIEW

**Comment by catenacyber** [comment]
This will fail both 7 and 8 until PR and its backport get merged

**Comment by victorjulien** [comment]
Can you force push a update to limit this PR to 8 at first?

**Comment by catenacyber** [comment]
> Can you force push a update to limit this PR to 8 at first?

Trying something...

Was not the label `requires backport` good enough for the SV merging script ?
Is this script available somewhere ?

**Comment by victorjulien** [comment]
> > Can you force push a update to limit this PR to 8 at first?
> 
> Trying something...
> 
> Was not the label `requires backport` good enough for the SV merging script ? Is this script available somewhere ?

Not yet, right now I run it manually and it's not yet aware of flags here.

**Comment by victorjulien** [comment]
Merged in #1541, thanks!

**Pull request closed without merging**
