### PR TITLE
detect-itype: add tests

### PR DESCRIPTION
**Pull request by hsadia538**
Redmine [Ticket](https://redmine.openinfosecfoundation.org/issues/5590) 
Describe Changes:

- Convert `DetectITypeMatchTest01` to suricata-verify test

### CODE REVIEW

**Comment by hsadia538** [comment]
I am aware that I need to create a Suricata PR as well for the cleanup of above mentioned test.
Do I make a separate PR for cleanup once this is approved or do I have to add it in my unit tests PR for the same file `detec-itype.` ?

**Review by inashivb — CHANGES_REQUESTED** [review]
Nice job! :)
Same changes requested as https://github.com/OISF/suricata/pull/8053

**Comment by hsadia538** [comment]
> Nice job! :) Same changes requested as [OISF/suricata#8053](https://github.com/OISF/suricata/pull/8053)

I have linked the PR. Is there anything else that is needed?

**Comment by hsadia538** [comment]
Followed by  #973

**Pull request closed without merging**
