### PR TITLE
Remove unused warning/error codes in Suricata

### PR DESCRIPTION
**Pull request by catenacyber**
Required by https://github.com/OISF/suricata/pull/7642 (and not the other way around)

### CODE REVIEW

**Comment by catenacyber** [comment]
I meant https://github.com/OISF/suricata/pull/7651 not 7642

**Comment by catenacyber** [comment]
ping @jasonish could we merge this ?

**Comment by jasonish** [comment]
Wouldn't an error code change be considered a breakage?  @victorjulien ?

**Comment by jasonish** [comment]
For reference, the issue around logging error codes: https://redmine.openinfosecfoundation.org/issues/3160

**Comment by jasonish** [comment]
Merged. Thanks.

**Comment by jasonish** [comment]
> > Merged. Thanks.
> 
> Wrong PR?

No, this PR was merged.

**Comment by catenacyber** [comment]
Thanks

**Comment by victorjulien** [comment]
Ah my mistake, didn't see this was the SV one

**Comment by catenacyber** [comment]
And so, should we merge https://github.com/OISF/suricata/pull/7961 now ?

**Pull request closed without merging**
