### PR TITLE
Datasets memcap tests/v5

### PR DESCRIPTION
**Pull request by inashivb**
## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/3910

Previous PR: https://github.com/OISF/suricata-verify/pull/1944

Changes since v4:
- rebased on top of latest master

### CODE REVIEW

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #1956, thanks!

**Comment by catenacyber** [comment]
This introduced a test for 7 cf `  lt-version: 8` in datasets-memcap-01/test.yaml and was not tested with latest Suricata 7

**Comment by catenacyber** [comment]
cf https://github.com/OISF/suricata/pulls?q=is%3Aopen+is%3Apr+base%3Amain+ https://github.com/OISF/suricata/actions/runs/9791836737/job/27039293186?pr=11424

**Comment by catenacyber** [comment]
```
 - /Users/runner/work/suricata/suricata/suricata-verify/tests/datasets-memcap-01/output/stderr
Error: thash: preallocating data failed: max thash memcap reached. Memcap 88074, Memuse 88160. [THashInitConfig:util-thash.c:280]
Error: detect-dataset: failed to set up dataset 'ua-seen'. [DetectDatasetSetup:detect-dataset.c:407]
Error: detect: error parsing signature "alert http any any -> any any (http.user_agent; dataset:isset,ua-seen,type string,load datasets.csv,memcap 88074,hashsize 1; sid:1;)" from file /Users/runner/work/suricata/suricata/suricata-verify/tests/datasets-memcap-01/test.rules at line 1 [DetectLoadSigFile:detect-engine-loader.c:185]
Error: suricata: Loading signatures failed. [LoadSignatures:suricata.c:2417]
```

**Comment by inashivb** [comment]
> ```
>  - /Users/runner/work/suricata/suricata/suricata-verify/tests/datasets-memcap-01/output/stderr
> Error: thash: preallocating data failed: max thash memcap reached. Memcap 88074, Memuse 88160. [THashInitConfig:util-thash.c:280]
> Error: detect-dataset: failed to set up dataset 'ua-seen'. [DetectDatasetSetup:detect-dataset.c:407]
> Error: detect: error parsing signature "alert http any any -> any any (http.user_agent; dataset:isset,ua-seen,type string,load datasets.csv,memcap 88074,hashsize 1; sid:1;)" from file /Users/runner/work/suricata/suricata/suricata-verify/tests/datasets-memcap-01/test.rules at line 1 [DetectLoadSigFile:detect-engine-loader.c:185]
> Error: suricata: Loading signatures failed. [LoadSignatures:suricata.c:2417]
> ```

In that case, the `os` check is not working properly, I think. https://github.com/OISF/suricata-verify/pull/1949/commits/41962d4bcea984105752340aa6794a720d9594e1
The test shouldn't have run on MacOS.

**Pull request closed without merging**
