### PR TITLE
tests: check for tls events to trigger once per flow

### PR DESCRIPTION
**Pull request by norg**
Test for issue https://redmine.openinfosecfoundation.org/issues/1983

### CODE REVIEW

**Comment by jasonish** [comment]
Appears to pass now: https://github.com/jasonish/suricata-verify/actions/runs/4963447610

**Comment by jasonish** [comment]
Reabsed here to show that this now passes.

**Comment by catenacyber** [comment]
Which certificate is supposed to have an invalid length in this big pcap with many flows ?

**Comment by catenacyber** [comment]
I would close this PR as it does not get any anomalies (instead of twice as much as wanted)

**Comment by catenacyber** [comment]
Closing this PR, work to be continued in the redmine ticket...

**Pull request closed without merging**
