### PR TITLE
Add RHEL build; enable Lua

### PR DESCRIPTION
**Pull request by jasonish**
Add an RHEL build (AlmaLinux) and enable Lua as Lua tests are one of the things that might work for you, but not for others based on your specific version of Lua.

### CODE REVIEW

**Comment by victorjulien** [comment]
Other question: should this be in this repo or in the suricata repo?

**Comment by jasonish** [comment]
> Guess I find the RHEL references a bit confusing. It's to test Centos/RHEL-like setups, but its not RHEL itself.

I've reword the commit to be RHEL-like.  In the acutal workflow file its clearly that its Alma.

**Comment by jasonish** [comment]
> Other question: should this be in this repo or in the suricata repo?

This is specifically for this repo to catch more conditions when tests are added that are more dependend on compile time switches. Saves me from doing dummy PRs in the Suricata repo.

**Comment by jasonish** [comment]
Merged via https://github.com/OISF/suricata-verify/pull/547.

**Pull request closed without merging**
