### PR TITLE
framework: warns on different type between yaml and json

### PR DESCRIPTION
**Pull request by catenacyber**
This is a draft for discussion

I lost some time debugging this issue using `2.0` instead of `"2.0"` in yaml for `ssh.client.proto_version`

### CODE REVIEW

**Comment by jasonish** [comment]
I have no issues with doing this.

**Comment by jasonish** [comment]
But I get lots of stuff like this:
```
Different type <type 'unicode'> alert <type 'str'> alert
Different type <type 'NoneType'> None <type 'int'> 1
```

**Comment by catenacyber** [comment]
Hmm... Then what do you think about latest commit ?

**Comment by jasonish** [comment]
Merged. Thanks!

**Pull request closed without merging**
