### PR TITLE
pgsql: add test for out order parameters in the startup message - v2

### PR DESCRIPTION
**Pull request by jufajardini**
Fixes broken test from previous PR #976

### CODE REVIEW

**Comment by jufajardini** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/8072

**Comment by victorjulien** [comment]
pgsql is new in 7, so why do we fail in 6?

**Comment by jasonish** [comment]
Missing min-version check in pgsql-bug-5579.

**Comment by jufajardini** [comment]
Juliana needs more coffee, it seems. sorry about that. >__<'

**Comment by jufajardini** [comment]
Replaced by: https://github.com/OISF/suricata-verify/pull/989

**Pull request closed without merging**
