### PR TITLE
Adds test with dns/enip polyglot flow

### PR DESCRIPTION
**Pull request by catenacyber**
Not sure if we want to merge this

cf https://github.com/OISF/suricata/pull/6832

### CODE REVIEW

**Comment by victorjulien** [comment]
@jasonish can you see if we can improve DNS detection

**Comment by jasonish** [comment]
> @jasonish can you see if we can improve DNS detection

Is this a real world scenario to consider? Both ENIP and DNS parsers are pinned to different ports which should make this a non-issue I'd think.

**Comment by jasonish** [comment]
So this test is showing something that is odd, and not what should be?

**Comment by catenacyber** [comment]
> > @jasonish can you see if we can improve DNS detection
> 
> Is this a real world scenario to consider? Both ENIP and DNS parsers are pinned to different ports which should make this a non-issue I'd think.

ENIP uses source ports, so you can have source port ENIP and destination port DNS and both probing parsers are run 

Cf Suricata.yaml
```
    enip:
      enabled: no
      detection-ports:
        dp: 44818
        sp: 44818
```

> So this test is showing something that is odd, and not what should be?

I am not sure what should be indeed...

**Comment by catenacyber** [comment]
Replaced by Gitlab MR by @jasonish

**Pull request closed without merging**
