### PR TITLE
tls: add test for tls keywords v4

### PR DESCRIPTION
**Pull request by hsadia538**
Previous PR : https://github.com/OISF/suricata-verify/pull/1076
Describe Changes:

- Update `test.rules` to fix typo

### CODE REVIEW

**Comment by hsadia538** [comment]
Not sure if its related or not but the build failure is due to the test `test-bad-hex-rule-2`

**Comment by hsadia538** [comment]
After incorporating feedback from last PR , I added tests for the new keywords that replace the legacy one. Should I change the commit message to reflect that?

**Comment by catenacyber** [comment]
Is this expecting a Suricata PR to pass ?

**Comment by jufajardini** [comment]
> Is this expecting a Suricata PR to pass ?

Shouldn't be, as this is just increasing testing coverage for existing keywords...

**Comment by jufajardini** [comment]
> After incorporating feedback from last PR , I added tests for the new keywords that replace the legacy one. Should I change the commit message to reflect that?

sorry for taking so long to answer D:
Better to, yes. :)
It is ok to have that in the commit body, if it doesn't fit in the title.

**Comment by jufajardini** [comment]
> Not sure if its related or not but the build failure is due to the test `test-bad-hex-rule-2`

I've triggered a re-run for that failure. If this still fails, I would suggest rebasing and submitting a new PR - which would also work well since you're about to change the commit messages, too :)

**Comment by hsadia538** [comment]
I see that the checks have passed

**Comment by hsadia538** [comment]
Followed by #1106

**Pull request closed without merging**
