### PR TITLE
tests: add tests for exception policy master switch - v5

### PR DESCRIPTION
**Pull request by jufajardini**
Previous PR: #1040 

Changes from last PR:
- add drop.reason to the first test, remove `set stream.midstream=true` to avoid confusion about what the test is about.

Suricata PR: https://github.com/OISF/suricata/pull/8287

### CODE REVIEW

**Comment by catenacyber** [comment]
Does this require a new Suricata PR Juliana ?

**Comment by catenacyber** [comment]
Is this related to #1178 ?

**Comment by jufajardini** [comment]
> Is this related to #1178 ?

No, this is for testing the master configuration for the exception policies (to set the same value to all different exception policies from one place). But we're missing backporting this, due to a bug in the midstream exception policy (latest PR for that: #9011)

**Comment by jufajardini** [comment]
rebased and replaced: https://github.com/OISF/suricata-verify/pull/1264

**Pull request closed without merging**
