### PR TITLE
body_md5 : take every line into account,

### PR DESCRIPTION
**Pull request by catenacyber**
also lines that are headers of sub mime parts

and do not take new line post boundary

### CODE REVIEW

**Comment by catenacyber** [comment]
@jasonish thoughts about this behavior change ?

**Comment by catenacyber** [comment]
cf https://github.com/OISF/suricata/pull/8450

**Comment by catenacyber** [comment]
> @jasonish thoughts about this behavior change ?

ping ?

**Comment by jasonish** [comment]
> > @jasonish thoughts about this behavior change ?
> 
> ping ?

I think I need more discussion of why the change in md5.. Determine what may be more correct.  My expectation is we'd parse the headers, then hash the bytes to the end of the file.  Is that new behavior?

**Comment by catenacyber** [comment]
> 
> I think I need more discussion of why the change in md5.. Determine what may be more correct. My expectation is we'd parse the headers, then hash the bytes to the end of the file. Is that new behavior?

Yes, this is the new behavior.
Difference with old behavior is when we have multiple/mixed recursive MIME.
The global md5 does not take into account the internal headers

In the example, we have something like

```
MIME Multipart Media Encapsulation, Type: multipart/mixed, Boundary: "----=_NextPart_000_0004_01CA45B0.095693F0"
- Preamble: 546869732069732061206d756c746970617274206d65737361676520696e204d494d4520…
- Encapsulated multipart part:  (multipart/alternative)
- Encapsulated multipart part:  (text/plain)
```

The `email.body_md5` must take into account the mime headers of the encapsulated parts

**Comment by jasonish** [comment]
> > I think I need more discussion of why the change in md5.. Determine what may be more correct. My expectation is we'd parse the headers, then hash the bytes to the end of the file. Is that new behavior?
> 
> Yes, this is the new behavior. Difference with old behavior is when we have multiple/mixed recursive MIME. The global md5 does not take into account the internal headers
> 
> In the example, we have something like
> 
> ```
> MIME Multipart Media Encapsulation, Type: multipart/mixed, Boundary: "----=_NextPart_000_0004_01CA45B0.095693F0"
> - Preamble: 546869732069732061206d756c746970617274206d65737361676520696e204d494d4520…
> - Encapsulated multipart part:  (multipart/alternative)
> - Encapsulated multipart part:  (text/plain)
> ```
> 
> The `email.body_md5` must take into account the mime headers of the encapsulated parts

That sounds more correct to me, so I'm in favour of the change. Sounds like the previous behaviour was attempting to be smart.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata-verify/pull/1252

**Pull request closed without merging**
