### PR TITLE
tests/vntag: Basic test case for VNTAG decode 

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #489 

This PR adds a basic test for VNTAG decoding and supports
- 7.0.0 beta
-6.0.3 backport

### CODE REVIEW

**Comment by catenacyber** [comment]
@jlucovsky what is the status ? should this pass now that https://github.com/OISF/suricata/pull/6173 got merged ?

**Comment by jlucovsky** [comment]
> @jlucovsky what is the status ? should this pass now that [OISF/suricata#6173](https://github.com/OISF/suricata/pull/6173) got merged ?

Yes -- this test should be succeeding with the merge of that pr.

**Comment by catenacyber** [comment]
So, could you rebase and force-push to run CI again ?

**Comment by jasonish** [comment]
Merged. Thanks!

**Pull request closed without merging**
