### PR TITLE
Add tests for DCERPC/UDP

### PR DESCRIPTION
**Pull request by inashivb**

### CODE REVIEW

**Comment by victorjulien** [comment]
What is the explanation for the failure on all branches?

**Comment by inashivb** [comment]
> What is the explanation for the failure on all branches?

`4.1.x` + `5.0.x` did not have dcerpc logging.
`master` logged `call_id` as well which has now been removed from logger.

**Comment by victorjulien** [comment]
Switched to draft as the test is incomplete. Please submit a new PR.

**Comment by inashivb** [comment]
Replaced with #367

**Pull request closed without merging**
