### PR TITLE
test: Add byte_math test

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #228 

This PR adds a test case for `byte_math` and updates a warning message that the `byte_math` PR changes.

Companion PR: [Suricata PR#4916](https://github.com/OISF/suricata/pull/4916)

### CODE REVIEW

**Comment by victorjulien** [comment]
I assume for this to pass we need updates to 4.1.x and 5.0.x as well?

**Comment by jlucovsky** [comment]
> I assume for this to pass we need updates to 4.1.x and 5.0.x as well?

Perhaps I should abandon the error message change.

**Comment by victorjulien** [comment]
Closing as its broken for 5.0

**Comment by jlucovsky** [comment]
Continued in #246

**Pull request closed without merging**
