### PR TITLE
Next/20221028/v2

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
- #978 
- #982

### CODE REVIEW

**Comment by jasonish** [comment]
Requires: https://github.com/OISF/suricata/pull/8118

**Comment by jufajardini** [comment]
> Please pull in #930 or use #985.

Did you mean https://github.com/OISF/suricata-verify/pull/984 ?

**Comment by jasonish** [comment]
> > Please pull in #930 or use #985.
> 
> Did you mean #984 ?

Oops.  #986 actually.

**Comment by jasonish** [comment]
All merged now.

**Pull request closed without merging**
