### PR TITLE
smtp/mime: adds test for url extraction in base64 message

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/5185

Suricata PR incoming

### CODE REVIEW

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
This tests fails on my OpenBSD runners. I suspect due to the link type of the pcap.

**Comment by victorjulien** [comment]
> This tests fails on my OpenBSD runners. I suspect due to the link type of the pcap.

I see more pcaps like this in SV, must be something else.

**Comment by victorjulien** [comment]
image

**Comment by victorjulien** [comment]
> image

Even tcpdump doesn't grog it
```
$ tcpdump -n -r ../suricata-verify/tests/smtp-url-base64/smtp-url-b64.pcap
tcpdump: bad dump file format
```

**Review by victorjulien — CHANGES_REQUESTED** [review]
Pcap needs to fixed somehow

**Comment by catenacyber** [comment]
Continued in https://github.com/OISF/suricata-verify/pull/1898

**Pull request closed without merging**
