### PR TITLE
Adds dnp3 midstream direction probing parser test

### PR DESCRIPTION
**Pull request by catenacyber**
needs PR https://github.com/OISF/suricata/pull/5093

I had difficulties using a special suricata.yaml file in this directory...

### CODE REVIEW

**Comment by catenacyber** [comment]
Should be ready to merge after https://github.com/OISF/suricata/pull/5139

**Comment by catenacyber** [comment]
Should we wait for back ports, or Should I set `min-version: 6.0.0` ?

**Comment by catenacyber** [comment]
cf https://redmine.openinfosecfoundation.org/issues/3793

**Comment by catenacyber** [comment]
Let's wait for back ports (should we add a label for this ?)

**Comment by victorjulien** [comment]
Merged in #271, thanks Philippe

**Pull request closed without merging**
