### PR TITLE
tests: Add test case for unreachable content 

### PR DESCRIPTION
**Pull request by jlucovsky**
Continuation of #673

This PR tests the dsize validation logic in Suricata PR 6838 (link below).

Changes:
- Existing test cases for dsize validation were restricted to Suricata versions less than 7
- These test cases were uses to create version 7 and later tests that expect the modified error message
- Typo fixups :-)

This PR accompanies [Suricata PR #6838](https://github.com/OISF/suricata/pull/6838)

### CODE REVIEW

**Comment by catenacyber** [comment]
Latest suricata PR is https://github.com/OISF/suricata/pull/6960

**Comment by jlucovsky** [comment]
Continued in #7714

**Comment by catenacyber** [comment]
@jlucovsky why did you close this ?

**Comment by jufajardini** [comment]
Latest Suri PR is: https://github.com/OISF/suricata/pull/7846

**Pull request closed without merging**
