### PR TITLE
dcerpc: dce_iface test to match many request/responses

### PR DESCRIPTION
**Pull request by zer1t0**
The dce_iface keyword should match for all those dcerpc requests and responses sent in the context of the given interface.

The following pcap includes a dcerpc connection that uses the netlogon interface (uuid: 12345678-1234-abcd-ef00-01234567cffb). After connecting to the interface, 6 requests/responses are made. The given rule should match 12 times, once for each request/response. 

This test is related to the ticket https://redmine.openinfosecfoundation.org/issues/4769 and PR https://github.com/OISF/suricata/pull/6511

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks @zer1t0 could you translate your pcap-ng file to a regular pcap file ?

**Comment by zer1t0** [comment]
Done

**Comment by catenacyber** [comment]
> Thanks @zer1t0 could you translate your pcap-ng file to a regular pcap file ?

Thanks for changing this PR.
There are others such as https://github.com/OISF/suricata-verify/pull/568 with the same problem.
Could you check them all ? (cf builds / PCAP-NG Check (pull_request))

**Comment by zer1t0** [comment]
Inputs of https://github.com/OISF/suricata-verify/pull/572, https://github.com/OISF/suricata-verify/pull/569 and https://github.com/OISF/suricata-verify/pull/568 converted into pcaps.

**Comment by catenacyber** [comment]
Thanks

**Comment by inashivb** [comment]
Merged as a part of https://github.com/OISF/suricata-verify/pull/620 after rebase. Thank you for your work! :)

**Pull request closed without merging**
