### PR TITLE
mqtt: add suricata.yaml enabling MQTT for testing

### PR DESCRIPTION
**Pull request by satta**
This PR ensures that the MQTT app-layer parser is always enabled in the MQTT tests, See https://github.com/OISF/suricata/pull/6229#issuecomment-867926602

### CODE REVIEW

**Comment by catenacyber** [comment]
You can also just add `--set app-layer.protocols.mqtt.enabled=yes` in test.yaml
What do you prefer @satta ?

**Comment by satta** [comment]
I think I would prefer having separate `suricata.yaml` config files just for consistency with the other MQTT test cases.

**Review by catenacyber — APPROVED** [review]
Good for me

**Comment by jasonish** [comment]
Merged. Thanks!

**Pull request closed without merging**
