### PR TITLE
GitHub ci jsonschema/v13

### PR DESCRIPTION
**Pull request by catenacyber**
Part of #789 with other commit in #796

### CODE REVIEW

**Comment by catenacyber** [comment]
Still need to add some recent changes...

**Comment by catenacyber** [comment]
> Still need to add some recent changes...

Should be done now

**Comment by catenacyber** [comment]
Cf https://redmine.openinfosecfoundation.org/issues/1369

**Comment by catenacyber** [comment]
@jasonish what do you think of this ?

**Comment by jasonish** [comment]
> @jasonish what do you think of this ?

I like it.  But I think the schema needs to move to Suricata source tree.  Otherwise how do we handle the multiple Suricata branches?

**Comment by catenacyber** [comment]
Done in https://github.com/OISF/suricata-verify/pull/826

**Pull request closed without merging**
