### PR TITLE
Adds test with http over IPv6

### PR DESCRIPTION
**Pull request by catenacyber**
and absence of anomalies

Requires libhtp PR https://github.com/OISF/libhtp/pull/329

### CODE REVIEW

**Comment by victorjulien** [comment]
This test passes w/o the libhtp PR. Does it test what it should?

**Comment by catenacyber** [comment]
Indeed, every OS defines its own `AF_INET6`
cf https://github.com/wireshark/wireshark/blob/eb5f4eea99593b92298bacecc5c9d885cc13a9ad/epan/dissectors/packet-null.c#L46

**Comment by victorjulien** [comment]
> Needs backport of [OISF/suricata@27b4f16](https://github.com/OISF/suricata/commit/27b4f165b17499cc765ccb770f1cf994992e10f6) @jlucovsky @inashivb should we have a specific ticket for this ?

Yes

**Comment by jasonish** [comment]
Backport still required?

**Comment by victorjulien** [comment]
> Backport still required?

Backport tickets are already made:
https://redmine.openinfosecfoundation.org/issues/4793
https://redmine.openinfosecfoundation.org/issues/4794 (PR https://github.com/OISF/suricata/pull/6543)

**Comment by catenacyber** [comment]
> > Backport still required?
> 
> Backport tickets are already made: https://redmine.openinfosecfoundation.org/issues/4793 https://redmine.openinfosecfoundation.org/issues/4794 (PR [OISF/suricata#6543](https://github.com/OISF/suricata/pull/6543))

I see these just got merged, so rebased and force-pushed to get CI running again

**Comment by jasonish** [comment]
Merged. Thanks!

**Pull request closed without merging**
