### PR TITLE
arp: add tests v4

### PR DESCRIPTION
**Pull request by glongo**
## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket:
https://redmine.openinfosecfoundation.org/issues/6827

### CODE REVIEW

**Comment by glongo** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/11005

**Comment by glongo** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/11060

**Comment by glongo** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/11085

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #1833, thanks!

**Pull request closed without merging**
