### PR TITLE
Detect lua 4911 v3

### PR DESCRIPTION
**Pull request by TheKharleeci**
Includes test for LuaMatchTest01-LuaMatchTest06

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

Previous PR: https://github.com/OISF/suricata-verify/pull/1086

### CODE REVIEW

**Review by inashivb — CHANGES_REQUESTED** [review]
Hi @TheKharleeci !
Thank you for your work! :) Could you please add a README to all the tests? I'm unsure what each test is supposed to be doing to ensure if it is doing the intended thing correctly?

**Review by jufajardini — CHANGES_REQUESTED** [review]
Hello there :)

Thanks for continuing to work on this task. Adding to what Shivani has requested, these tests could all be into a single commit. Could you please squash the commits and edit the commit message so it's more conforming to our standards?

We must also investigate why these are not passing, as they should be.

**Comment by TheKharleeci** [comment]
I seem to have messed up my commit history and I'm not sure how to fix it. Do I create another branch?

**Comment by jufajardini** [comment]
> I seem to have messed up my commit history, I can't seem to squash the commits and I'm not sure how to fix it. Do I create another branch?

That is the easier, cleaner, and safer way - also useful for the next PR, as you keep different branch versions :P

If you are feeling adventurous, though, you can rework your history with an interactive rebase: `git rebase -i HEAD~numberofcommitstoorganize`. This can be messy when we're not used to it, so I recommend you create a new branch for that in any case, to practice a bit, if you are not familiar with it.

**Comment by TheKharleeci** [comment]
Replaced With  #1242

**Pull request closed without merging**
