### PR TITLE
tests: Add a test for http2 authority mismatch event

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6425

### CODE REVIEW

**Comment by catenacyber** [comment]
Requires https://github.com/OISF/suricata/pull/9746

**Comment by victorjulien** [comment]
Fails on 6.0.x as well. Does the Suri PR need backporting?

**Comment by catenacyber** [comment]
> Fails on 6.0.x as well. Does the Suri PR need backporting?

Yes, you asked for a backport in https://redmine.openinfosecfoundation.org/issues/6425#note-1

**Comment by victorjulien** [comment]
Merged in #1456, thanks!

**Pull request merged**
