### PR TITLE
Dir grouping/v2

### PR DESCRIPTION
**Pull request by shivan1b**
Closes redmine ticket: https://redmine.openinfosecfoundation.org/issues/3069

### CODE REVIEW

**Comment by jasonish** [comment]
Looks good to me.

**Comment by catenacyber** [comment]
Looks good to me as well.

I just have a question about how --skip-tests option interacts with --force option or patterns options

**Comment by victorjulien** [comment]
Think it would be nice to have a visual indicator of the dir. Now we have
```
===> http-evader-045: OK
===> http-evader-046: OK
```
but it would be nicer to have
```
===> http-evader/http-evader-045: OK
===> http-evader/http-evader-046: OK
```
So ```$dirname/$testname```.

Fine to do this in a follow up PR btw.

**Comment by victorjulien** [comment]
LGTM

**Comment by shivan1b** [comment]
> Looks good to me as well.
> 
> I just have a question about how --skip-tests option interacts with --force option or patterns options

Usage with `--force`, gives the results as if `--force` was not provided on cmdline.

With patterns, it takes into account the pattern and skip the tests amon the patterns that match. e.g. `../suricata-verify/run/py evader --skip-tests evader` will give 0.

**Comment by catenacyber** [comment]
Thanks

**Pull request merged**
