### PR TITLE
tests: add test for issue 4751

### PR DESCRIPTION
**Pull request by hsadia538**
Previous PR https://github.com/OISF/suricata-verify/pull/972

Redmine [ticket](https://redmine.openinfosecfoundation.org/issues/4751)

Describe changes:

- Update test.yaml

### CODE REVIEW

**Comment by hsadia538** [comment]
Do we need a ticket for this one or should I add something to the main issue ticket? ( i already added the pr link)

**Comment by inashivb** [comment]
> Do we need a ticket for this one or should I add something to the main issue ticket? ( i already added the pr link)

We do not need a separate ticket for s-v tests added right with the change/feature.

**Comment by jasonish** [comment]
If I'm reading this correctly this configures Suricata to only log the https records right? If so, it would be good to test for that as well.  One way is to create a check on the number of dns records.  It should equal the number of https records.

**Comment by hsadia538** [comment]
> If I'm reading this correctly this configures Suricata to only log the https records right? If so, it would be good to test for that as well. One way is to create a check on the number of dns records. It should equal the number of https records.

I have created a Suricata verify test to verify the output for ` rrtype : HTTPS.`
For context: This aims to parse rrtype 65 as HTTPS.

**Comment by jasonish** [comment]
Ok, the pcap contains a single packet, so what I suggested doesn't make sense here.

**Review by jasonish — APPROVED** [review]

**Comment by jasonish** [comment]
Merged. Thanks!

**Pull request closed without merging**
