### PR TITLE
createst: commandline param to specify required features

### PR DESCRIPTION
**Pull request by VictoryWekwa**
It should be possible to define multiple features.

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4061

createst.py mytest mypcap --features HAVE_LUA,HAVE_LIBJANSSON

The final generated test.yaml should have features defined globally.

```
requires:
  features:
    - HAVE_LIBJANSSON
    - HAVE_LUA
  version: 6.0.0

checks:
- filter:
    count: 1
```

### CODE REVIEW

**Comment by inashivb** [comment]
Hi @VictoryWekwa !
I get the following error when I try to run your code:
```
python ../suricata-verify/createst.py mytest ../suricata-verify/tests/alert-testmyids/input.pcap 
  File "../suricata-verify/createst.py", line 146
    if args["features"]:
                       ^
TabError: inconsistent use of tabs and spaces in indentation

```
Could you please look at it?

**Comment by VictoryWekwa** [comment]
> Hi @VictoryWekwa !
> I get the following error when I try to run your code:
> 
> ```
> python ../suricata-verify/createst.py mytest ../suricata-verify/tests/alert-testmyids/input.pcap 
>   File "../suricata-verify/createst.py", line 146
>     if args["features"]:
>                        ^
> TabError: inconsistent use of tabs and spaces in indentation
> ```
> 
> Could you please look at it?

Hello, yes please, sorry about that.  I just made a commit now to push my changes. Thanks.

**Review by inashivb — CHANGES_REQUESTED** [review]
Hi @VictoryWekwa !
Would you be interested in/have time to look into this? This would require a rebase and fix for
`TypeError: __init__() got an unexpected keyword argument 'metavar'`

Thanks for your work on this! :)

**Comment by jufajardini** [comment]
Closing this due to lack of activity in the past 6 months. Thanks for your time dedicated to this! :)

**Pull request closed without merging**
