### PR TITLE
Add various tests for SSLv2 protocol detection

### PR DESCRIPTION
**Pull request by giannitedesco**
Two versions for a plain SSLv2 handshake: on-port and off-port (port
12345).

And then a second pair for backwards compatible SSLv2 client handshake
upgrading to TLS 1.0: also on-port and off-port (port 12345)

Tests OISF/suricata#6326

### CODE REVIEW

**Comment by giannitedesco** [comment]
For some reason I can't get suricata to output TLS handhsake events in order to match on those.

The data is synthetically generated in a packet synthesis language so maybe I've done something wrong? But it looks fine in wireshark which is, of course, the ultimate arbiter of all network protocol correctness :rofl:

**Comment by giannitedesco** [comment]
Suricata PR is OISF/suricata/pull/6326

**Comment by catenacyber** [comment]
hey @giannitedesco are you planning further work on this and https://github.com/OISF/suricata/pull/6770 ?

**Comment by giannitedesco** [comment]
> hey @giannitedesco are you planning further work on this and [OISF/suricata#6770](https://github.com/OISF/suricata/pull/6770) ?

Yes, sorry, I forgot all about it and where it got hung up.

**Comment by catenacyber** [comment]
So, why do we need a Suricata PR if these S-V tests pass ?

**Comment by giannitedesco** [comment]
> So, why do we need a Suricata PR if these S-V tests pass ?

These should fail until the fixes in the suri PR are merged..

**Comment by giannitedesco** [comment]
afaict everything is basically in the state we want modulo stuff like adding a redmine ticket, rebasing the code? the build check failures on the other PR look spurious to me.

**Comment by catenacyber** [comment]
> > So, why do we need a Suricata PR if these S-V tests pass ?
> 
> These should fail until the fixes in the suri PR are merged..

They do not fail : CI is green, and suricata master gets me
```
python3 ../suricata-verify/run.py sslv2
===> sslv2-handshake: OK
===> sslv2-offport-handshake: OK
===> tls-offport-sslv2-upgrade: OK
===> tls-sslv2-upgrade: OK

PASSED:  4
FAILED:  0
SKIPPED: 0
```

**Comment by catenacyber** [comment]
Closing this as closed https://github.com/OISF/suricata/pull/6770 waiting for a new version

**Pull request closed without merging**
