### PR TITLE
Adds a test case with an evil HTTP server

### PR DESCRIPTION
**Pull request by catenacyber**
NOT TO BE MERGED (yet)

Protocol detection should work even if the evil server first acts like a FTP server.

As for now, it does not.

### CODE REVIEW

**Comment by catenacyber** [comment]
Could be merged once that suricata PR gets merged

**Comment by jasonish** [comment]
@catenacyber Whats the status of this?

**Comment by catenacyber** [comment]
Still valid.
Latest PR was https://github.com/OISF/suricata/pull/4605

But this should come after https://github.com/OISF/suricata/pull/5759 https://github.com/OISF/suricata-verify/pull/417

We can close this PR in the meantime if you prefer

**Comment by catenacyber** [comment]
Closing for now

**Pull request closed without merging**
