### PR TITLE
detect: adds test with bsize: 0

### PR DESCRIPTION
**Pull request by catenacyber**
Suricata PR incoming

### CODE REVIEW

**Comment by catenacyber** [comment]
Requires https://github.com/OISF/suricata/pull/8770

**Comment by catenacyber** [comment]
I could have also added a negated content...

**Comment by catenacyber** [comment]
Suricata PR was merged

**Comment by jasonish** [comment]
Merged with https://github.com/OISF/suricata-verify/pull/1198. Thanks!

**Pull request closed without merging**
