### PR TITLE
Feat 3357/v7

### PR DESCRIPTION
**Pull request by TharushiJay**
Implements parallel tests capability using the python multiprocessing module.

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/3357

Changes from last PR :

- Refactored the code to include `run_mp()` and `run_single()`

### CODE REVIEW

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
My MinGW builders are still unhappy
```
$ python ..\suricata-verify\run.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\msys64\mingw32\lib\python3.8\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\msys64\mingw32\lib\python3.8\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\msys64\mingw32\lib\python3.8\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Gitlab-Runner\builds\hNRUpEPe\0\inliniac\suricata-ci\suricata-verify\run.py", line 50, in <module>
    manager = mp.Manager()
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\managers.py", line 579, in start
    self._process.start()
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\msys64\mingw32\lib\python3.8\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
It hangs here.

**Comment by jasonish** [comment]
Oops, I had a typo in my GitHub CI job to test this PR against my libsuricata branch.  Anyways, I have a few lines that appear to fix this.

**Comment by jasonish** [comment]
https://github.com/OISF/suricata-verify/pull/434 should fix the Windows build.  But I'm going to run it through GitHub CI right away.

**Comment by jasonish** [comment]
Closing. This ticket was about Windows support which was fixed by not doing parallel builds on Windows.

**Pull request closed without merging**
