### PR TITLE
tests: add pgsql cancel request tests - v3

### PR DESCRIPTION
**Pull request by jufajardini**
Showcase CancelRequest postgresql message output.

Related to
Task #6577

Previous PR: https://github.com/OISF/suricata-verify/pull/1536

Changes from previous PR:
- update `CancelRequest` message's fields, to be the same seen in the `AuthenticationOk` response - to ease correlation

Redmine ticket:
https://redmine.openinfosecfoundation.org/issues/6577

### CODE REVIEW

**Comment by jufajardini** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/10039

**Comment by victorjulien** [comment]
This failing on both 7 and 8 will block merge of the suri pr.

**Comment by jufajardini** [comment]
> This failing on both 7 and 8 will block merge of the suri pr.

I keep making that mistake >___<

**Comment by jufajardini** [comment]
Min-version check updated on https://github.com/OISF/suricata-verify/pull/1545

**Pull request closed without merging**
