### PR TITLE
multi-tenant: Basic multi-tenant selector tests

### PR DESCRIPTION
**Pull request by jlucovsky**
This commit adds basic tests for vlan-selector configurations (including vlan-pair, added in 6237)

Issue: 6237

## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/6237

### CODE REVIEW

**Comment by jasonish** [comment]
What happens when you have 2 inner vlan's with the same ID, but different outer IDs?  Or is that not a normal deployment scenario?

**Comment by jlucovsky** [comment]
Good point.  It’s a customer issue  and they must be aware of that.  Should the doc bring that point up more strongly?-jeffOn Aug 19, 2023, at 3:10 PM, Jason Ish ***@***.***> wrote:﻿
What happens when you have 2 inner vlan's with the same ID, but different outer IDs?  Or is that not a normal deployment scenario?

**Comment by catenacyber** [comment]
Suricata PR for reference is https://github.com/OISF/suricata/pull/9401

**Comment by catenacyber** [comment]
https://github.com/OISF/suricata/pull/10015

**Comment by catenacyber** [comment]
Should this have `min-version: 8` ?

**Review by catenacyber — CHANGES_REQUESTED** [review]
Should be green for 7, right ?

**Comment by jlucovsky** [comment]
Closed for further evaluation.

**Pull request closed without merging**
