### PR TITLE
framework: bump jsonschema crate to v0.17

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: no ticket, just fixing eve-validator

### CODE REVIEW

**Comment by catenacyber** [comment]
@jasonish how does that look to you ?

**Review by jasonish — APPROVED** [review]

**Comment by catenacyber** [comment]
On my environment, I currently get this
```
   Compiling ahash v0.7.6
error[E0635]: unknown feature `stdsimd`
  --> /Users/catena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.6/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `ahash` (lib) due to 1 previous error
error: Failed to build EVE validator, validation will be disabled
```

And this PR fixes it

**Comment by jasonish** [comment]
> On my environment, I currently get this
> 
> ```
>    Compiling ahash v0.7.6
> error[E0635]: unknown feature `stdsimd`
>   --> /Users/catena/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.7.6/src/lib.rs:33:42
>    |
> 33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
>    |                                          ^^^^^^^
> 
> For more information about this error, try `rustc --explain E0635`.
> error: could not compile `ahash` (lib) due to 1 previous error
> error: Failed to build EVE validator, validation will be disabled
> ```
> 
> And this PR fixes it

Any idea why it started failing? We do commit the lockfile, so the crate didn't change.

**Comment by catenacyber** [comment]
Rust update ? (for clippy 1.77 ?)

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #1755, thanks!

**Pull request closed without merging**
