### PR TITLE
Add tests for nfs* frames v7

### PR DESCRIPTION
**Pull request by ghostinthehive**
Previous PR https://github.com/OISF/suricata-verify/pull/774
Changes from Previous PR:
- Add rules and checks for `rpc.creds` to check for `creds_flavor`

Goes with https://github.com/OISF/suricata/pull/7108

### CODE REVIEW

**Comment by catenacyber** [comment]
@jasonish PR was merged for this, can we run CI again ?

**Comment by jasonish** [comment]
> @jasonish PR was merged for this, can we run CI again ?

still fails: https://github.com/OISF/suricata-verify/runs/6165482370?check_suite_focus=true

**Comment by catenacyber** [comment]
@ghostinthehive would you inspect the CI failure ?

**Comment by ghostinthehive** [comment]
> @ghostinthehive would you inspect the CI failure ?

Okay, on it!

**Comment by ghostinthehive** [comment]
Sorry for not catching on this earlier,

Ran a quick check, looks like there is a problem with `nfs2 - nfs3` frames tests .. checking it
`nfs4` ran fine ..

**Comment by catenacyber** [comment]
@ghostinthehive are you still working on this ?

**Pull request closed without merging**
