### PR TITLE
Detect tls v11

### PR DESCRIPTION
**Pull request by hsadia538**
Previous PR #1126 

Changes:
- Correct commit order

### CODE REVIEW

**Review by inashivb — APPROVED** [review]
Great job incorporating the changes! :)
LGTM. Thank you!

**Comment by inashivb** [comment]
Is there something we can include here, like a befor and after screenshot or something to show the change in code coverage?

**Comment by hsadia538** [comment]
**Coverage comparison before and after:**
Screenshot 2023-02-20 at 1 28 39 PM
Screenshot 2023-02-20 at 1 29 25 PM

**Comment by inashivb** [comment]
Your PR was merged as a part of https://github.com/OISF/suricata-verify/pull/1156. Thank you for your contribution! :)

**Pull request closed without merging**
