### PR TITLE
Dataset ops v2.3

### PR DESCRIPTION
**Pull request by regit**
Replace #880 by fixing dataset-09-load test

### CODE REVIEW

**Comment by catenacyber** [comment]
Is there a Suricata PR for this ?
I do not see src/detect-ipaddr.c

**Comment by regit** [comment]
Yes, latest version is https://github.com/OISF/suricata/pull/7747

**Comment by catenacyber** [comment]
Thanks, I had searched datasets with an s in suricata PRs...

**Comment by inashivb** [comment]
Replaced w #963

**Pull request closed without merging**
