### PR TITLE
mqtt: test mqtt frames v2

### PR DESCRIPTION
**Pull request by hsadia538**
Ticket: https://redmine.openinfosecfoundation.org/issues/5731

Previous PR: #1064 

Describe changes:
- Add tests for mqtt frames

Requires: https://github.com/OISF/suricata/pull/8382

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
For this first set of frame types, this is looking good, to me :)

**Comment by jufajardini** [comment]
In light of the last discussions around truncated messages, I think it would be good to have a test with frames and those truncated types, so we could see what are the frames registering in such a case. :)

**Review by jufajardini — CHANGES_REQUESTED** [review]
Please, see my comment :)

**Comment by hsadia538** [comment]
> In light of the last discussions around truncated messages, I think it would be good to have a test with frames and those truncated types, so we could see what are the frames registering in such a case. :)

Ok I will incorporate this in a new SV PR and then you will re-run CI checks for this one?

**Comment by jufajardini** [comment]
> > In light of the last discussions around truncated messages, I think it would be good to have a test with frames and those truncated types, so we could see what are the frames registering in such a case. :)
> 
> Ok I will incorporate this in a new SV PR and then you will re-run CI checks for this one?

I think that can work. If not, we'd need a new Suricata PR.

**Pull request closed without merging**
