### PR TITLE
applayer: add tests for ticket 7044

### PR DESCRIPTION
**Pull request by inashivb**
## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/7044

Previous PR: https://github.com/OISF/suricata-verify/pull/1953

Changes since v3:
- comments addressed

### CODE REVIEW

**Comment by catenacyber** [comment]
Redmine ticket 7044 is not a bug : it is an optimization, tests pass already, right ?

**Comment by inashivb** [comment]
> Redmine ticket 7044 is not a bug : it is an optimization, tests pass already, right ?

yes. I recently changed that. It was marked a bug earlier as the initial assumption was that dcerpc was missing truncate call. Will force push the change in commit message.

**Comment by catenacyber** [comment]
> > Redmine ticket 7044 is not a bug : it is an optimization, tests pass already, right ?
> 
> yes. I recently changed that. It was marked a bug earlier as the initial assumption was that dcerpc was missing truncate call. Will force push the change in commit message.

And you can change the PR title ;-)

**Comment by inashivb** [comment]
> 
> And you can change the PR title ;-)

Sorry. Done. :)

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #1978, thanks!

**Pull request closed without merging**
