### PR TITLE
gh/workflow: use enable-debug-validation w build

### PR DESCRIPTION
**Pull request by inashivb**

### CODE REVIEW

**Comment by inashivb** [comment]
Should we do debug-validation with all the jobs or have a separate one?

**Comment by jasonish** [comment]
> Should we do debug-validation with all the jobs or have a separate one?

Any idea if we currenlty pass with debug-validation on?

**Comment by inashivb** [comment]
> > Should we do debug-validation with all the jobs or have a separate one?
> 
> Any idea if we currenlty pass with debug-validation on?

Seems like it. I added it in this job and it seems to have passed. Perhaps, I'm not understanding what you mean. :thinking:

**Comment by catenacyber** [comment]
To me, it looks ready, not just a draft, right ?

**Comment by inashivb** [comment]
> To me, it looks ready, not just a draft, right ?

To me as well. Marked ready for review.

**Review by jasonish — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #932, thanks!

**Pull request closed without merging**
