### PR TITLE
tests/log: Verify bug 5198

### PR DESCRIPTION
**Pull request by jlucovsky**
This issue requires an ASAN build -- it doesn't reproduce without ASAN.

Issue: 5198 ([Suricata PR 7475](https://github.com/OISF/suricata/pull/7475))

### CODE REVIEW

**Comment by catenacyber** [comment]
So, CI should run with ASAN...

**Comment by catenacyber** [comment]
@jasonish should we have ASAN in this CI ?

**Comment by jasonish** [comment]
> @jasonish should we have ASAN in this CI ?

I don't think so.  We have ASAN enabled jobs in the Suricata repo.  This GitHub-CI in this repo is more a quick sanity check that the versions are correct.  Not an exhaustive list of compile time options, otherwise we'd just end up recreating all tests from Suricata I think.

**Comment by catenacyber** [comment]
Suricata PR was merged

**Comment by jasonish** [comment]
Merged. Thanks!

**Pull request closed without merging**
