### PR TITLE
tests: add bug 2576 tests

### PR DESCRIPTION
**Pull request by victorjulien**
https://redmine.openinfosecfoundation.org/issues/2576

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Thanks for bringing these to SV suite!

**Review by jasonish — APPROVED** [review]

**Comment by catenacyber** [comment]
Looks like tests pass after merge of https://github.com/OISF/suricata/pull/10503

Could you rebase this ?

**Comment by catenacyber** [comment]
PS : I did the rebase in #1735

**Comment by catenacyber** [comment]
Merged in https://github.com/OISF/suricata-verify/pull/1623

**Pull request closed without merging**
