### PR TITLE
draft PR

### PR DESCRIPTION
**Pull request by claudius96**
This is just a draft of what I have been working on with feature #3082. I couldn't finish the issue but these are the changes that I managed to make.

### CODE REVIEW

**Comment by claudius96** [comment]
run.py L460,459, 873, 903, 921, 954, 804.

**Comment by inashivb** [comment]
Hi @claudius96 !
Would you be willing to complete this task now?

**Comment by inashivb** [comment]
> Yes i think i would like to try it this time around

Thank you! Just to put the expectations straight, we are not participating with a Python project in this round. We do have C and Rust projects though so you're welcome to apply to those. You can also finish this as a part of your contribution. :)

**Comment by claudius96** [comment]
Great, thanks!

**Comment by inashivb** [comment]
Hi @claudius96 !
Would you be interested in/have time to look into this? I'm cleaning up old PRs from the repo. Thank you for the work you put into this feature. :)

**Comment by jasonish** [comment]
Closing due to inactivity.  If you wish to continue, please check the status of the ticket first. Thanks!

**Pull request closed without merging**
