### PR TITLE
Add tests for HTTP/2 decompression bug, 7.0.0-beta1 hits anomaly

### PR DESCRIPTION
**Pull request by dcbeckett**
Bug #5691

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks David for the good test

**Comment by catenacyber** [comment]
Suricata PR was merged, @jasonish should we do backports ?

**Comment by catenacyber** [comment]
Backport got merged cf https://github.com/OISF/suricata/pull/8203

**Comment by victorjulien** [comment]
Merged in #1030, for 7 only. Will need an update when the fix is backported.

**Comment by catenacyber** [comment]
> Will need an update when the fix is backported.

The fix was back ported.

But in master6, http2 decompression is a feature that needs to be enabled at configure/compile time...

**Pull request closed without merging**
