### PR TITLE
tests: test that triggers a rule with established though 3whs missing

### PR DESCRIPTION
**Pull request by norg**
This creates a test for issue https://redmine.openinfosecfoundation.org/issues/2639 where the 3whs is missing but the rule with established keyword still triggers.

### CODE REVIEW

**Comment by jasonish** [comment]
This test current fails. Does it depend on an issue being fixed?

**Comment by norg** [comment]
Yes as described in the issue you **don't** want to have the alert

**Comment by catenacyber** [comment]
There is a typo in the directory name : `estabilshed`

**Comment by victorjulien** [comment]
Merged in #291, thanks!

**Pull request closed without merging**
