### PR TITLE
detect-xor: do not depend on C code

### PR DESCRIPTION
**Pull request by inashivb**
@catenacyber one of the exhibits of the problem you mentioned 🥲

### CODE REVIEW

**Review by victorjulien — APPROVED** [review]

**Comment by catenacyber** [comment]
Nice find, how did you find it ?

**Comment by inashivb** [comment]
> Nice find, how did you find it ?

Was just trying to reproduce the memleak issue you fixed w xor transform..

**Comment by catenacyber** [comment]
So, there are a lot more :
```
git grep '\- src/' | cut -d: -f2- | cut -d/ -f2- | sort | uniq -c
   4 detect-transform-casechange.c
   3 detect-transform-dotprefix.c
   1 detect-transform-xor.c
```

**Comment by catenacyber** [comment]
`git grep '\- src/' | cut -d: -f2- | cut -d/ -f2- | sort | uniq | while read i; do echo -n $i; ls ../../suricata/src/$i; done | grep No` full one-liner

**Comment by inashivb** [comment]
Please consider PR #2143 instead of this. That one is more complete.

**Pull request closed without merging**
