### PR TITLE
tests: deduplicate pcaps, cleanup extras - v3

### PR DESCRIPTION
**Pull request by jufajardini**
Previous PR: https://github.com/OISF/suricata-verify/pull/1352

Change from previous PR:
- change pcap reference in geoip test, as the pcap it was linking to is now also using a reference (cf https://github.com/OISF/suricata-verify/pull/1352#issuecomment-1703899375)

### CODE REVIEW

**Review by inashivb — APPROVED** [review]
LGTM. Thanks for picking this up! :)

**Comment by jufajardini** [comment]
> LGTM. Thanks for picking this up! :)

🙇🏽  Team work! ^^

**Comment by victorjulien** [comment]
No longer passes on master-6.0.x

**Review by victorjulien — CHANGES_REQUESTED** [review]
Fails on some of my builders
```
===> exception-policy-stream-reassembly-memcap-08: FAILED: got exit code 1, expected 0
===> exception-policy-stream-reassembly-memcap-09: FAILED: got exit code 1, expected 0
===> exception-policy-stream-reassembly-memcap-07: FAILED: got exit code 1, expected 0
```

**Comment by jasonish** [comment]
Would it make sense to have some pre-merge process, perhaps even parse of `createst` that renames any new pcaps to a filename based on its hash and dumps the file in `pcaps/`.  Test could then reference the pcap by hash?

**Comment by inashivb** [comment]
> Would it make sense to have some pre-merge process, perhaps even parse of `createst` that renames any new pcaps to a filename based on its hash and dumps the file in `pcaps/`. Test could then reference the pcap by hash?

That's genius! I'm thinking why didn't i think of this before. 😅 
A standard pcap location would also make the script I use to find the duplicates and change the pcap fields much much easier.

Could there be any drawbacks?

**Comment by inashivb** [comment]
Merged in https://github.com/OISF/suricata-verify/pull/1402. Thanks! :)

**Pull request closed without merging**
