### PR TITLE
detect-modbus/v2: add tests to modbus

### PR DESCRIPTION
**Pull request by TheKharleeci**
Add tests for DetectModbusTestAccess and DetectModbusTestFunction

Link to redmine ticket: #4911

Previous PR: #636

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Overall, it looks good to me, thanks. :)

Thinking that we may need a more descriptive commit message, but let's see what others think.

**Comment by TheKharleeci** [comment]
Corresponding Suricata PR: OISF/suricata#6830

**Comment by TheKharleeci** [comment]
I think I can go ahead to close this PR?

**Comment by inashivb** [comment]
> I think I can go ahead to close this PR?

Yes. Sorry about that.

Merged in #671 thanks!

**Pull request closed without merging**
