### PR TITLE
applayer: enable tests for 7.0.x

### PR DESCRIPTION
**Pull request by inashivb**
## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/7407

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
LGTM, thanks!

**Review by catenacyber — CHANGES_REQUESTED** [review]
This looks incomplete compared to https://github.com/OISF/suricata-verify/pull/2172

Test bug-7199 should get removed `min-version: 8`
Also `tests/firewall/firewall-06-tls-sni-enforce/test.yaml`and maybe other

**Comment by jufajardini** [comment]
> This looks incomplete compared to #2172
> 
> Test bug-7199 should get removed `min-version: 8` Also `tests/firewall/firewall-06-tls-sni-enforce/test.yaml`and maybe other

What's done here isn't enough? https://github.com/OISF/suricata-verify/pull/2178#pullrequestreview-2495613846

**Comment by catenacyber** [comment]
I propose https://github.com/OISF/suricata-verify/pull/2179

**Comment by catenacyber** [comment]
The important point is test bug-7199 is missing and this is a backport for 7199

**Comment by jufajardini** [comment]
> LGTM, thanks!

Considering Philippe's comment, I think it's better we go with his PR.

**Pull request closed without merging**
