### PR TITLE
tests: update for stricter timeout handling

### PR DESCRIPTION
**Pull request by victorjulien**
#2116 rebased

### CODE REVIEW

**Review by catenacyber — APPROVED** [review]
Makes sense.

Do you know which commit exactly changed this behavior ?
Like https://github.com/OISF/suricata/pull/12278/commits/de9ceab8c784814487615ddc8558c24c36d342c2 ?

**Comment by victorjulien** [comment]
> Makes sense.
> 
> Do you know which commit exactly changed this behavior ? Like [OISF/suricata@de9ceab](https://github.com/OISF/suricata/commit/de9ceab8c784814487615ddc8558c24c36d342c2) ?

I don't think any did in suri, we started seeing it with these specific tests right after they were introduced.

**Comment by victorjulien** [comment]
> Makes sense.
> 
> Do you know which commit exactly changed this behavior ? Like [OISF/suricata@de9ceab](https://github.com/OISF/suricata/commit/de9ceab8c784814487615ddc8558c24c36d342c2) ?

Probably https://github.com/OISF/suricata/pull/12278/commits/4f926a6462b581e085135a36fed7ab31cd103008

The diff is caused by flows that were previously considered not timed out due to imprecision, now getting considered timed out. So a new flow is created.

**Comment by victorjulien** [comment]
Replaced by #2203

**Pull request closed without merging**
