### PR TITLE
dataset-06-state-long: add test on learning dataset

### PR DESCRIPTION
**Pull request by regit**
Test that suricata can learn a set of 1200 DNS rrname and store
correctly the result on disk.

### CODE REVIEW

**Comment by inashivb** [comment]
Does this go with any Suricata PR?

**Comment by jasonish** [comment]
> Does this go with any Suricata PR?

No, its just increasing our dataset coverage.

**Comment by jasonish** [comment]
This test is failing on GitHub CI, but passes for me locally.  I think its something about the environment and a shell check, and not really the fault of this test.  I'll do some checking myself as to why this type of check is failing.

**Comment by jasonish** [comment]
Merged with change to deal with `sort` on different systems producing different results.

**Pull request closed without merging**
