### PR TITLE
detect-hostbits/v2: convert unittests

### PR DESCRIPTION
**Pull request by TheKharleeci**
Adds test for:

Detect-hostbits-01: HostBitsTestSig05
Detect-hostbits-02: HostBitsTestSig07
Detect-hostbits-03: HostBitsTestSig08

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

Previous PR: #660

### CODE REVIEW

**Comment by inashivb** [comment]
Corresponding Suricata PR: https://github.com/OISF/suricata/pull/6821

**Review by inashivb — APPROVED** [review]
LGTM. Thanks! :)

**Comment by TheKharleeci** [comment]
Corresponding Suricata PR: OISF/suricata#6826

**Comment by inashivb** [comment]
Merged in #671, thanks!

**Pull request merged**
