### PR TITLE
detect/datasets: adds test for unset operation

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/7195

Suricata feature was merged for https://github.com/OISF/suricata/pull/11815 and in 7 also with https://github.com/OISF/suricata/pull/11833

https://github.com/OISF/suricata-verify/pull/2065 new version with custom made pcap and rules only using `save` instead of `load` and `save`

### CODE REVIEW

**Review by inashivb — APPROVED** [review]
LGTM 🚀

**Review by inashivb — CHANGES_REQUESTED** [review]
Wait a second. Everything looks good but I think because there is no pcap, this test will simply be skipped so although it's nice you've added how you tested it but this test is of no value to our suite if we don't have a pcap..

**Comment by catenacyber** [comment]
> Wait a second. Everything looks good but I think because there is no pcap, this test will simply be skipped so although it's nice you've added how you tested it but this test is of no value to our suite if we don't have a pcap..

Oops, added

**Comment by inashivb** [comment]
> > Wait a second. Everything looks good but I think because there is no pcap, this test will simply be skipped so although it's nice you've added how you tested it but this test is of no value to our suite if we don't have a pcap..
> 
> Oops, added

Thanks. Looking perfect now. :)
Will you make another PR w a single commit?

**Comment by catenacyber** [comment]
Done in https://github.com/OISF/suricata-verify/pull/2071

**Pull request closed without merging**
