### PR TITLE
Backport fixes/v1

### PR DESCRIPTION
**Pull request by inashivb**
#638 + version check removals

### CODE REVIEW

**Comment by inashivb** [comment]
@jlucovsky seems like https://redmine.openinfosecfoundation.org/issues/4953 was backported and merged in `5.0.x` but the tests still fail for some reason..

**Comment by victorjulien** [comment]
> @jlucovsky seems like https://redmine.openinfosecfoundation.org/issues/4953 was backported and merged in `5.0.x` but the tests still fail for some reason..

This is due to the gaps in the traffic. 5.0.x HTTP parser doesn't support GAPs.

**Review by victorjulien — CHANGES_REQUESTED** [review]
Can you rebase this and make the commit message bit more specific?

**Comment by inashivb** [comment]
Replaced w #714

**Pull request closed without merging**
