### PR TITLE
tests: Threshold.config validation tests

### PR DESCRIPTION
**Pull request by jlucovsky**
This PR adds tests that use improperly formatted threshold.config files to ensure that in test config mode -- `-T` -- Suricata will exit with a non-zero error code.

### CODE REVIEW

**Comment by catenacyber** [comment]
Is this related to #374 ?

**Comment by jlucovsky** [comment]
> #374

No ... this test ensures that improperly formatted threshold.config files can be detected when using `-T` or `--init-errors-fatal`

**Comment by jlucovsky** [comment]
> Does it require a Suricata PR ?

Yes -- see https://github.com/OISF/suricata/pull/5946

**Comment by jasonish** [comment]
Merged with https://github.com/OISF/suricata-verify/pull/498.

**Pull request closed without merging**
