### PR TITLE
Bug 78/v5

### PR DESCRIPTION
**Pull request by inashivb**

### CODE REVIEW

**Comment by catenacyber** [comment]
What has changed from the previous PR ?

**Comment by inashivb** [comment]
@catenacyber your comments were addressed 
```
Looks overall good to me, event if it can be improved by removing some parts of the checks (like undefined gid of the signature where default value gets used)
```

**Review by catenacyber — APPROVED** [review]
Ok so still looks good to me

**Comment by jasonish** [comment]
Merged via https://github.com/OISF/suricata-verify/pull/474.

**Pull request closed without merging**
