### PR TITLE
pcap: convert pcapng capture to pcap.

### PR DESCRIPTION
**Pull request by eroullit**
Some platforms have a libpcap without pcapng support activated.
In this situation, the tests fail because the capture file cannot be
opened.
Those tests do not require pcapng therefore they can be safely converted
to the pcap standard.

### CODE REVIEW

**Comment by victorjulien** [comment]
Which platforms would this be? My openbsd qa builders work w/o issue.

**Comment by victorjulien** [comment]
Nevermind, I see that my mingw has the same issue.

**Comment by victorjulien** [comment]
It seems this fix is incomplete, it just removes the pcap-ng files, but does not replace them with the pcap ones.

**Comment by eroullit** [comment]
Indeed. Here they are.

**Comment by catenacyber** [comment]
Looks good to me now

**Comment by victorjulien** [comment]
All pcaps are now old pcap format, and a travis check was added. So this PR is not relevant anymore. I guess I fixed it a while back as part of some other work, and forgot to include this PR.

**Pull request closed without merging**
