### PR TITLE
add test for extra tls alert

### PR DESCRIPTION
**Pull request by victorjulien**
#2080 rebased

### CODE REVIEW

**Comment by victorjulien** [comment]
Needs to be 8.0 only for now.

**Comment by inashivb** [comment]
Why was this marked draft @victorjulien ? Shall I change something here?

**Comment by catenacyber** [comment]
> Why was this marked draft victorjulien ? Shall I change something here?

I think you need a new PR with "8.0 only for now."

**Comment by inashivb** [comment]
> > Why was this marked draft victorjulien ? Shall I change something here?
> 
> I think you need a new PR with "8.0 only for now."

ah. I thought that was just a comment for something already done. Thank you!

**Comment by catenacyber** [comment]
Rebased in https://github.com/OISF/suricata-verify/pull/2173

**Pull request closed without merging**
