### PR TITLE
ssh: do not enforce pcap_cnt

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: None

Prerequisite for https://github.com/OISF/suricata/pull/10307 and next

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Looks good to me, thanks for adding an explanation in the commit message!

**Comment by jasonish** [comment]
Should we then be checking that `pcap_cnt` doesn't exist on the event? Not sure if S-V handles this case, but its probably worth doing than just removing the check.

**Comment by catenacyber** [comment]
I think the important test is that we get the alert.
Getting it on packet 7, or pseudo packet timing out the flow is less important.

If we really want to test this, are we sure we want to consider packet 7 as invalid and not run tx detection on it ?

**Comment by jasonish** [comment]
> If we really want to test this, are we sure we want to consider packet 7 as invalid and not run tx detection on it ?

I don't know specifically.  But S-V is about detecting changes in behaviour as well.  If it used to be 7, and some fix made the field go away, I think that should be encoded in the test, to detect if it ever comes back unintentionally.

**Comment by catenacyber** [comment]
Continued in https://github.com/OISF/suricata-verify/pull/1640

**Comment by catenacyber** [comment]
> > If we really want to test this, are we sure we want to consider packet 7 as invalid and not run tx detection on it ?
> 
> I don't know specifically. But S-V is about detecting changes in behaviour as well. If it used to be 7, and some fix made the field go away, I think that should be encoded in the test, to detect if it ever comes back unintentionally.

Did something in next version of the PR

**Pull request closed without merging**
