### PR TITLE
ssh-banner: remove version check

### PR DESCRIPTION
**Pull request by inashivb**
Redmine ticket: https://redmine.openinfosecfoundation.org/issues/4563

### CODE REVIEW

**Comment by catenacyber** [comment]
Does this PR need the back ports to pass CI ?

**Comment by inashivb** [comment]
> Does this PR need the back ports to pass CI ?

@catenacyber no. These are the current smtp-rfc2231 and mqtt failures. Nothing to do with this test. This can be merged. Fix has been merged in the master sometime ago and in 6.0.x even before that.

**Comment by catenacyber** [comment]
Let's wait for the smtp-rfc2231 and mqtt  fixes, then run CI again then, right ?

**Comment by inashivb** [comment]
> Let's wait for the smtp-rfc2231 and mqtt fixes, then run CI again then, right ?

Yes, sure

**Comment by victorjulien** [comment]
Tests pass is set but we have failures on 5 and 6?

**Comment by victorjulien** [comment]
Merged in #607

**Pull request closed without merging**
