### PR TITLE
Adds 3 tests for SMB EICAR file

### PR DESCRIPTION
**Pull request by BasTNCY**
3 tests for smb EICAR file write :
Regular write, segmentation in random size, SMBv1
Regular write, two NetBIOS messages in one TCP packet, SMBv1
Regular write, segmentation in 2 pieces after the SMB header, SMBv1

Squashed commits for Pull Request #192

### CODE REVIEW

**Comment by BasTNCY** [comment]
CC @catenacyber

**Comment by catenacyber** [comment]
Looks good to me

**Comment by catenacyber** [comment]
CI fails because of waiting https://github.com/OISF/suricata/pull/4842#issuecomment-617258857

**Comment by victorjulien** [comment]
Merged, thanks! For future SMB tests please add the `RUST` feature, as Suricata 4.1 only supports SMB when Rust is built-in.

**Pull request closed without merging**
