### PR TITLE
detect-proto/v2: add tests for detect engine proto

### PR DESCRIPTION
**Pull request by TheKharleeci**
Adds test for DetectProtoTestSig01

Link to redmine ticket: https://redmine.openinfosecfoundation.org/issues/4911

Previous PR:  #649

### CODE REVIEW

**Comment by TheKharleeci** [comment]
Corresponding Suricata PR: OISF/suricata#6827

**Review by jufajardini — APPROVED** [review]
Looks good to me! =]

**Comment by victorjulien** [comment]
Your commit ID is different in this PR, can you address that?

**Review by victorjulien — CHANGES_REQUESTED** [review]
Commit ID issue as mentioned in comment

**Comment by TheKharleeci** [comment]
Followed by: #677

**Pull request closed without merging**
