### PR TITLE
rfb: test rfb frames v5

### PR DESCRIPTION
**Pull request by hsadia538**
Ticket: https://redmine.openinfosecfoundation.org/issues/5717

Previous PR: #10509

Describe new changes:
- Rebase branch

Requires: https://github.com/OISF/suricata/pull/8526

### CODE REVIEW

**Comment by hsadia538** [comment]
Should I rebase this?

**Comment by jufajardini** [comment]
> Should I rebase this?

While there are no conflicts since Suri PR was merged, could you please create a new PR so that we confirm that tests pass with master, before staging this for merge?

**Comment by jufajardini** [comment]
Suricata PR was merged: https://github.com/OISF/suricata/pull/8703

**Comment by hsadia538** [comment]
followed by #1176

**Pull request closed without merging**
