### PR TITLE
tests: add test for bug 5783

### PR DESCRIPTION
**Pull request by b1tg**
Should fail on master and 6.0.x for now.

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/5783

Suri fix: https://github.com/OISF/suricata/pull/8449

Previous PR:

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Commit style looks good now, just minor comments from my end :)

**Comment by catenacyber** [comment]
And these need to be plain pcap, not pcap-ng files ;-)

**Comment by b1tg** [comment]
I saw these tips in readme, maybe we should update this?

> Copy a single pcap file into the test directory. It must end in ".pcap" or ".pcapng".

**Comment by catenacyber** [comment]
> I saw these tips in readme, maybe we should update this?
> 
> > Copy a single pcap file into the test directory. It must end in ".pcap" or ".pcapng".

Indeed, it should be updated, cc @inashivb @jufajardini

**Comment by jufajardini** [comment]
> > I saw these tips in readme, maybe we should update this?
> > > Copy a single pcap file into the test directory. It must end in ".pcap" or ".pcapng".
> 
> Indeed, it should be updated, cc @inashivb @jufajardini

My apologies, I didn't know we couldn't use pcapng files either '-' gonna update it.

**Comment by jufajardini** [comment]
Replaced by https://github.com/OISF/suricata-verify/pull/1091

**Pull request closed without merging**
