### PR TITLE
test/event: Test for reassembly depth reached event

### PR DESCRIPTION
**Pull request by jlucovsky**
Issue: 3512

This commit adds a test to validate that the stream reassembly depth
event fire.

### CODE REVIEW

**Comment by catenacyber** [comment]
cf https://github.com/OISF/suricata/pull/7623

**Comment by jlucovsky** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/7680

**Comment by catenacyber** [comment]
Suricata PR was merged https://github.com/OISF/suricata/pull/7690

**Comment by victorjulien** [comment]
Merged in #932, thanks!

**Pull request closed without merging**
