### PR TITLE
tests: showcase unexpected tcp rule behavior

### PR DESCRIPTION
**Pull request by jufajardini**
Showcase different scenarios for Suricata behavior in IPS mode with TCP rules and TLS traffic, with PASS or DROP actions.

Decided to share this as a WIP, as creating these for `case a` took me much longer than anticipated.

## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket:
- none yet

### CODE REVIEW

**Comment by victorjulien** [comment]
Lets remove the unnecessary verbosity from the test.yaml, the goal is to understand a specific issue.

**Comment by victorjulien** [comment]
Would also like to see a pcap that uses different IP addresses than localhost. Makes things much easier to reason about if the src/dst are different.

**Comment by catenacyber** [comment]
Why does the test pass if it is unexpected behavior ? What is the expected behavior ?

**Comment by jufajardini** [comment]
Closing this in favour of: https://github.com/OISF/suricata-verify/pull/1952 as it's more aligned with what we want to see for these tests.

**Comment by jufajardini** [comment]
> Why does the test pass if it is unexpected behavior ? What is the expected behavior ?

There is a suspicion that the behavior of the TCP rule not passing is not what the rule language seems to express (cf https://github.com/OISF/suricata-verify/pull/1952/files#r1663786361)

**Pull request closed without merging**
