### PR TITLE
arp: add tests

### PR DESCRIPTION
**Pull request by glongo**
## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket:
https://redmine.openinfosecfoundation.org/issues/6827

### CODE REVIEW

**Comment by glongo** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/10659

**Comment by glongo** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/10675

**Comment by glongo** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/10692

**Comment by glongo** [comment]
Suricata PR: https://github.com/OISF/suricata/pull/10705

**Review by jasonish — CHANGES_REQUESTED** [review]
I'd like to see a test on the arp reply as well.

**Comment by glongo** [comment]
> I'd like to see a test on the arp reply as well.

Done in https://github.com/OISF/suricata-verify/pull/1739

**Pull request closed without merging**
