### PR TITLE
Dcerpc logging/v3

### PR DESCRIPTION
**Pull request by inashivb**

### CODE REVIEW

**Comment by victorjulien** [comment]
Why is this failing on 4.1 and 5.0? Do we need any updates there?

**Comment by inashivb** [comment]
> Why is this failing on 4.1 and 5.0? Do we need any updates there?

Yeah I think dcerpc never had logging before. I should add version check in test.yaml. Thanks.

**Comment by catenacyber** [comment]
Does this depend on a Suricata PR ?

**Comment by inashivb** [comment]
Replaced with #296

**Pull request closed without merging**
