### PR TITLE
tests: add test for bug 5783 - v2

### PR DESCRIPTION
**Pull request by b1tg**
Previous PR: https://github.com/OISF/suricata-verify/pull/1079

Changes from previous PR:
- fix description
- remove useless fields in test.yaml

### CODE REVIEW

**Comment by catenacyber** [comment]
Requires https://github.com/OISF/suricata/pull/8449

**Comment by jufajardini** [comment]
re-run the checks by a blip, sorry about that...

**Review by jufajardini — CHANGES_REQUESTED** [review]
Thanks for updating the README and test.yaml! 

I see that we're still using the pcapng file format, which leads one of the CI checks to fail. Could you please fix that?

When you submit the new PR, please also rebase, I see an unrelated test failing and want to make sure this is alright with the next PR :)

**Comment by b1tg** [comment]
move to https://github.com/OISF/suricata-verify/pull/1105

**Pull request closed without merging**
