### PR TITLE
tests: add test for 7187

### PR DESCRIPTION
**Pull request by victorjulien**
Redmine ticket:
https://redmine.openinfosecfoundation.org/issues/7187

### CODE REVIEW

**Comment by catenacyber** [comment]
Strange pcap, is not call_id supposed to be incremented by the client ?

**Comment by inashivb** [comment]
> Strange pcap, is not call_id supposed to be incremented by the client ?

While that's what's mentioned in the RFC and that's how correct request/response pairs should be mapped, I can find several pcaps with repeated call IDs.. within s-v and outside. I don't think I understand this dcerpc behavior properly.

**Review by catenacyber — APPROVED** [review]
Test looks good to me

**Comment by victorjulien** [comment]
Merged in #2036, thanks!

**Pull request closed without merging**
