### PR TITLE
test/stream: Update drop reason per new reason code

### PR DESCRIPTION
**Pull request by jlucovsky**
Issue: 6235

## Ticket

If your pull request is related to a Suricata ticket, please provide
the full URL to the ticket here so this pull request can monitor
changes to the ticket status:

Redmine ticket:
- [6235](https://redmine.openinfosecfoundation.org/issues/6235)

### CODE REVIEW

**Review by jufajardini — CHANGES_REQUESTED** [review]
Considering the issue associated with this change, I think it would be good to also add checks for the drop reason stats counters, here, too.

**Comment by jlucovsky** [comment]
> Member

Good point. I've updated the tests with a stats check.

**Comment by catenacyber** [comment]
Why is CI green when https://github.com/OISF/suricata/pull/9408 is not merged yet ?

**Comment by jufajardini** [comment]
> Why is CI green when [OISF/suricata#9408](https://github.com/OISF/suricata/pull/9408) is not merged yet ?

Trying to figure that out... 🤔

**Comment by jufajardini** [comment]
> > > Why is CI green when [OISF/suricata#9408](https://github.com/OISF/suricata/pull/9408) is not merged yet ?
> > 
> > 
> > Trying to figure that out... 🤔
> 
> Because these S-V tests require feature DEBUG which is not tested by S-V CI (but I guess is tested by Suricata CI)

aha 🙇🏽 
I must not forget this...

**Comment by jlucovsky** [comment]
> > > > Why is CI green when [OISF/suricata#9408](https://github.com/OISF/suricata/pull/9408) is not merged yet ?
> > > 
> > > 
> > > Trying to figure that out... 🤔
> > 
> > 
> > Because these S-V tests require feature DEBUG which is not tested by S-V CI (but I guess is tested by Suricata CI)
> 
> aha 🙇🏽 I must not forget this...

Why is debug required? I see the requirement in the test.yaml file and would like to understand why debug is required for a core feature?

**Comment by catenacyber** [comment]
Debug is required for this SV test.

If it is not required for the feature, you can try to get rid of it.
Or create a new test that does not require it

**Comment by jufajardini** [comment]
Sorry for adding more to this, but while doing a re-review after the push, it came to my mind: this hasn't been backported yet, right?

So, shouldn't we add min-version to the new/changed checks?

**Comment by victorjulien** [comment]
Merged in #1388, thanks!

**Pull request closed without merging**
