### PR TITLE
Allow testing the skipped tests

### PR DESCRIPTION
**Pull request by shivan1b**
Add a `--test-skip` option to allow testing even the skipped tests
defined by a certain feature.

**Sample output**

```
 $  python ../suricata-verify/run.py --test-skip HTTP_EVADER_OK evader-375
===> http-evader-375: PASSED. Is HTTP_EVADER_OK required?
PASSED. Is HTTP_EVADER_OK required?
FAILED. Requires HTTP_EVADER_OK.
OK

PASSED:  0
FAILED:  0
SKIPPED: 0
SKIPPED OK: 2
SKIPPED FAIL: 1
```

Closes redmine ticket: https://redmine.openinfosecfoundation.org/issues/3082

### CODE REVIEW

**Comment by victorjulien** [comment]
I'm trying to understand what the output tells me. The test has 3 checks, it seems that 2 pass and one fails. So this test still requires HTTP_EVADER_OK to pass.

What do the skipped ok and skipped fail mean? I would expect that they count tests instead of checks, but it looks like they count checks.

**Comment by shivan1b** [comment]
@victorjulien  current output of suricata-verify does give a count of checks for all scenarios BTW since the commit https://github.com/OISF/suricata-verify/commit/3df8765d4c288ebd57e3a854e1e7e1348985ee5c , would you like it to count the number of tests and not checks only for the `SKIPPED OK` and `SKIPPED FAIL` listing or all of them?

**Comment by catenacyber** [comment]
I had missed that change on counting

**Comment by victorjulien** [comment]
I would like to see the counters only count the tests.

**Comment by shivan1b** [comment]
@victorjulien @catenacyber how do you feel about #129 ? I could rebase this over that and have only test count as output.

**Comment by catenacyber** [comment]
Hey @shivan1b Is this PR still relevant ?

**Comment by inashivb** [comment]
@catenacyber no, its not. I have a new one.

**Pull request closed without merging**
