### PR TITLE
framework: more robustness against failing Suricata

### PR DESCRIPTION
**Pull request by catenacyber**
so as to catch unhandled exception if stdout/stderr has not an ascii character

Adds a timeout of 5 minutes per test

Replaces #935

### CODE REVIEW

**Comment by jasonish** [comment]
Would https://github.com/OISF/suricata-verify/pull/901 catch the error?

**Comment by catenacyber** [comment]
I do not think so.
You can test with current Suricata master branch, test ut-complete

**Comment by jasonish** [comment]
I'm not sure I agree with classifying these as io errors.  Instead we should handle this more gracefully. I'm thinking we open the stdout and stderr log files in binary mode, so we can pass the bytes through as is.  Then decode for display purposes.

For example: https://github.com/OISF/suricata-verify/pull/937

The timeout is still a good idea though.

**Comment by catenacyber** [comment]
Problem with #937 is that it tests pass on master when I think they should fail

**Comment by jasonish** [comment]
Please see https://github.com/OISF/suricata-verify/pull/937#issuecomment-1249897016.  I think I'm OK with validating the data as UTF-8.. But it needs to happen after writing the output to the file so we maintain the bad data in a log.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/suricata-verify/pull/948

**Pull request closed without merging**
