### PR TITLE
ssh-banner: remove version check

### PR DESCRIPTION
**Pull request by inashivb**
Redmine ticket: https://redmine.openinfosecfoundation.org/issues/4563

### CODE REVIEW

**Comment by catenacyber** [comment]
Why is this failing Shivani ?

**Comment by inashivb** [comment]
> Why is this failing Shivani ?

@catenacyber it is supposed to. It'll work with https://github.com/OISF/suricata/pull/6584

**Comment by catenacyber** [comment]
Thanks, I thought this was merged already

**Comment by inashivb** [comment]
Replaced w #600

**Pull request closed without merging**
