### PR TITLE
test/vlan: 3-level VLAN test

### PR DESCRIPTION
**Pull request by catenacyber**
Issue: 2816

This commit tests for 3-level VLAN encapsulations.

Rebase https://github.com/OISF/suricata-verify/pull/902

### CODE REVIEW

**Comment by catenacyber** [comment]
Suricata PR was merged, so this should pass, right @jlucovsky ?

**Comment by jlucovsky** [comment]
> Suricata PR was merged, so this should pass, right @jlucovsky ?

Correct.

**Comment by catenacyber** [comment]
And it does : CI is green :-)

**Comment by jasonish** [comment]
Merged with https://github.com/OISF/suricata-verify/pull/1243.

**Pull request closed without merging**
