### PR TITLE
dns: enable test for ticket 7018

### PR DESCRIPTION
**Pull request by catenacyber**
## Ticket

Redmine ticket: https://redmine.openinfosecfoundation.org/issues/7449
https://redmine.openinfosecfoundation.org/issues/7018
https://redmine.openinfosecfoundation.org/issues/7199

### CODE REVIEW

**Review by jufajardini — APPROVED** [review]
Thanks for figuring this out :)

**Comment by catenacyber** [comment]
@jufajardini do you understand why this PR is passing and it is not on 7 ?
cf https://github.com/OISF/suricata/pull/12263#issuecomment-2536705370

**Comment by catenacyber** [comment]
So, this PR is just DNS v2->v3 and tests pass

But the other tests task-7018-ids-dns-keywords do not pass for master8 unless you also do the v2->v3 conversion...

**Review by victorjulien — APPROVED** [review]

**Comment by victorjulien** [comment]
Merged in #2193, thanks!

**Comment by catenacyber** [comment]
yes

**Pull request closed without merging**
